// ─────────────────────────────────────────────────────────────────────────────
// ตึกร้าง / สร้างไม่เสร็จ ของหน่วยงานรัฐและองค์การมหาชน
//
// ที่มา: คอมเมนต์ในโพสต์ของ Nat Luengnaruemitchai ที่ขอรูปและพิกัดตึกราชการ
// ที่ร้างหรือสร้างไม่เสร็จ เพื่อทำ "รายการเที่ยวตึกร้างทั่วไทย" (17 ก.ย. 2569)
//
// ⚠ ทุกรายการยังเป็นข้อมูลบอกต่อ ยังไม่ได้ตรวจสอบกับเอกสารราชการ (verified: false)
// ⚠ ยังไม่มีรายการไหนมีพิกัดจริง — lat/lng เป็น null ทุกแถว ตำแหน่งบนแผนที่
//   แสดงได้แค่ระดับจังหวัด (precision: 'province')
//
// ── โครงสร้างหนึ่งรายการ ──────────────────────────────────────────────────────
// id           string   รหัสอ้างอิง
// name         string   ชื่ออาคาร/โครงการ
// agency       string   หน่วยงานเจ้าของโครงการ
// type         string   ministry | local | hospital | school | soe | autonomous | unknown
// status       string   unfinished (สร้างไม่เสร็จ) | abandoned (ทิ้งร้าง) | unused (เสร็จแต่ไม่ใช้)
// province     string   ชื่อจังหวัดไทย ต้องตรงกับ provinces.js — null = ไม่ระบุ/ทั่วประเทศ
// district     string   อำเภอ/เขต ('' ถ้าไม่ระบุ)
// budget       number   งบประมาณ หน่วยบาท (null = ไม่ระบุ)
// budgetApprox boolean  true = ต้นทางใช้คำว่า "ราว/กว่า" ตัวเลขไม่ตายตัว
// yearStart    number   ปี พ.ศ. ที่เริ่มก่อสร้าง
// yearDue      number   ปี พ.ศ. ที่ต้องแล้วเสร็จตามสัญญา
// yearStalled  number   ปี พ.ศ. ที่หยุดงาน / เริ่มไม่ได้ใช้
// progress     number   % ความคืบหน้าที่ต้นทางระบุ
// revived      boolean  true = กลับมาก่อสร้างต่อแล้ว
// photos       array    URL รูป หรือ data URI
// note         string   ข้อความจากต้นทาง (เก็บคำเดิมไว้ ไม่ตีความเพิ่ม)
// source       string   แหล่งที่มา
// sourceUrl    string   ลิงก์อ้างอิง
// lat, lng     number   พิกัด WGS84 — null จนกว่าจะมีคนส่งพิกัดจริงมา
// precision    string   'exact' = พิกัดจริง | 'province' = รู้แค่จังหวัด | 'none' = ไม่รู้ตำแหน่ง
// verified     boolean  true = ตรวจสอบกับเอกสาร/ภาพถ่ายแล้ว
// ─────────────────────────────────────────────────────────────────────────────

const BUILDINGS = [
  {
    id: "C-01",
    name: "สำนักงาน กสทช. แห่งใหม่",
    agency: "สำนักงาน กสทช.",
    type: "autonomous",
    status: "unfinished",
    province: "นนทบุรี",
    district: "",
    budget: 2643000000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: 76,
    revived: false,
    photos: [],
    note: "งานค้างหลังยกเลิกสัญญา ความคืบหน้าราว 76%",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-02",
    name: "อาคารสำนักงบประมาณแห่งใหม่",
    agency: "สำนักงบประมาณ",
    type: "ministry",
    status: "unfinished",
    province: "กรุงเทพมหานคร",
    district: "",
    budget: 2100000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "เปิดใช้บางส่วน แต่งานบางส่วนยังไม่สมบูรณ์",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-03",
    name: "อควาเรียมหอยสังข์",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unused",
    province: "สงขลา",
    district: "",
    budget: 1400000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ใช้งบแล้วกว่า 1,400 ล้านบาท เริ่มโครงการมาราว 20 ปี แต่ยังไม่เคยเปิดใช้งานตามแผน",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-04",
    name: "สถาบันพัฒนาข้าราชการฝ่ายตุลาการ ปากช่อง",
    agency: "สำนักงานศาลยุติธรรม",
    type: "ministry",
    status: "unfinished",
    province: "นครราชสีมา",
    district: "อ.ปากช่อง",
    budget: 782800000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ค่าก่อสร้าง 782.8 ล้านบาท ก่อสร้างล่าช้ากว่ากำหนด",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-05",
    name: "อาคารศาลแพ่งมีนบุรีและศาลอาญามีนบุรี",
    agency: "สำนักงานศาลยุติธรรม",
    type: "ministry",
    status: "unfinished",
    province: "กรุงเทพมหานคร",
    district: "เขตมีนบุรี",
    budget: 782000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: 33,
    revived: false,
    photos: [],
    note: "งานคืบหน้าราวหนึ่งในสามก่อนถูกบอกเลิกสัญญา",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-06",
    name: "อาคารผู้ป่วยนอกและอุบัติเหตุ 9 ชั้น รพ.สงขลา",
    agency: "โรงพยาบาลสงขลา",
    type: "hospital",
    status: "unfinished",
    province: "สงขลา",
    district: "",
    budget: 420000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "วงเงินเดิมกว่า 420 ล้านบาท สัญญาเดิมถูกยกเลิก ต้องประมูลงานส่วนที่เหลือใหม่",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-07",
    name: "สำนักงาน ป.ป.ช. ภาค 9 และ ป.ป.ช.สงขลา",
    agency: "สำนักงาน ป.ป.ช.",
    type: "autonomous",
    status: "unfinished",
    province: "สงขลา",
    district: "",
    budget: 40000000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "สัญญาเดิม 40 ล้านบาท ผู้รับเหมาทิ้งงาน ต้องจ้างใหม่และใช้งบเพิ่มเติม",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-08",
    name: "สำนักงาน สตง. จังหวัดพะเยา",
    agency: "สำนักงานการตรวจเงินแผ่นดิน",
    type: "autonomous",
    status: "unfinished",
    province: "พะเยา",
    district: "",
    budget: 70000000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ผู้รับเหมาทิ้งงาน",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-09",
    name: "สำนักงาน สตง. จังหวัดร้อยเอ็ด",
    agency: "สำนักงานการตรวจเงินแผ่นดิน",
    type: "autonomous",
    status: "unfinished",
    province: "ร้อยเอ็ด",
    district: "",
    budget: 58490000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ก่อสร้างค้างและยกเลิกสัญญา",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-10",
    name: "สำนักงาน สตง. จังหวัดตาก",
    agency: "สำนักงานการตรวจเงินแผ่นดิน",
    type: "autonomous",
    status: "unfinished",
    province: "ตาก",
    district: "",
    budget: 46900000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ผู้รับเหมาทิ้งงาน",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-11",
    name: "อาคารอเนกประสงค์ 6 ชั้น โรงเรียนเทศบาล 2 วัดกะพังสุรินทร์",
    agency: "โรงเรียนเทศบาล 2 วัดกะพังสุรินทร์",
    type: "school",
    status: "unfinished",
    province: "ตรัง",
    district: "",
    budget: 72240000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "สร้างได้ประมาณ 3 ชั้นก่อนหยุด ต้องตั้งงบใหม่กว่า 76 ล้านบาท",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-12",
    name: "อาคารเรียนโรงเรียนวัดสุทธิวราราม",
    agency: "โรงเรียนวัดสุทธิวราราม",
    type: "school",
    status: "unfinished",
    province: "กรุงเทพมหานคร",
    district: "",
    budget: 37380000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ก่อสร้างล่าช้าและค้างเป็นเวลานาน",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-13",
    name: "อาคารเรียนโรงเรียนอนุบาลเชิงเนิน 2 อาคาร",
    agency: "โรงเรียนอนุบาลเชิงเนิน",
    type: "school",
    status: "unused",
    province: "ระยอง",
    district: "",
    budget: 32040000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "งบรวม 32.04 ล้านบาท สร้างแล้วไม่ได้ใช้งานหลายปี",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-14",
    name: "อาคารเรียนโรงเรียนอนุบาลหัวตะพาน",
    agency: "โรงเรียนอนุบาลหัวตะพาน",
    type: "school",
    status: "unfinished",
    province: "อำนาจเจริญ",
    district: "อ.หัวตะพาน",
    budget: 17840000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "มีปัญหาก่อสร้างค้าง",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-15",
    name: "อาคารเรียนโรงเรียนเทศบาลบ้านคลองภาษี",
    agency: "โรงเรียนเทศบาลบ้านคลองภาษี",
    type: "school",
    status: "unfinished",
    province: "ตรัง",
    district: "",
    budget: null,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ผู้รับเหมาทิ้งงาน และหาผู้รับจ้างสร้างต่อไม่ได้ในช่วงหนึ่ง",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-16",
    name: "ศูนย์แสดงศิลปวัฒนธรรมพระยารัษฎานุประดิษฐ์",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unfinished",
    province: "ตรัง",
    district: "",
    budget: 107000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ใช้งบก่อสร้างเดิมราว 107 ล้านบาท แต่โครงการค้างมานานหลายปี",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-17",
    name: "ศูนย์ OTOP นครพนม",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unused",
    province: "นครพนม",
    district: "",
    budget: 30000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "สร้างแล้วไม่ได้ใช้งานตามวัตถุประสงค์นานกว่า 10 ปี",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-18",
    name: "ศูนย์แสดงผลิตภัณฑ์ชุมชน OTOP สุไหงโก-ลก",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unused",
    province: "นราธิวาส",
    district: "อ.สุไหงโก-ลก",
    budget: 49000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "อาคารบางส่วนไม่ได้ใช้งานและชำรุด",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-19",
    name: "ศูนย์ส่งเสริมอาชีพการนวดเพื่อสุขภาพ เบตง",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "abandoned",
    province: "ยะลา",
    district: "อ.เบตง",
    budget: 16000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "สร้างเสร็จแต่มีปัญหาส่งมอบและถูกทิ้งร้าง",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-20",
    name: "ศูนย์ส่งเสริมการท่องเที่ยวคลองท่าเสม็ด",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unused",
    province: "ชุมพร",
    district: "",
    budget: 19780000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "สร้างเสร็จแต่ยังไม่ได้ใช้ประโยชน์อย่างเต็มที่",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-21",
    name: "ศูนย์พัฒนาเด็กเล็ก เทศบาลตำบลบ้านธาตุ",
    agency: "เทศบาลตำบลบ้านธาตุ",
    type: "local",
    status: "unused",
    province: "อุดรธานี",
    district: "",
    budget: 1495000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: 2558,
    progress: null,
    revived: false,
    photos: [],
    note: "สร้างเสร็จตั้งแต่ปี 2558 แต่ไม่ได้ใช้งานหลายปี",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-22",
    name: "บ้านพักเด็กและครอบครัวนครศรีธรรมราช",
    agency: "บ้านพักเด็กและครอบครัว",
    type: "ministry",
    status: "abandoned",
    province: "นครศรีธรรมราช",
    district: "",
    budget: null,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ถูกระบุในฐานข้อมูลอาคารรัฐที่ถูกทิ้งร้าง",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-23",
    name: "สนามกีฬาอำเภออู่ทอง",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unused",
    province: "สุพรรณบุรี",
    district: "อ.อู่ทอง",
    budget: null,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "สร้างเสร็จแต่ไม่ได้เปิดใช้งานเป็นเวลานาน มีปัญหาเรื่องการรับผิดชอบพื้นที่",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-24",
    name: "สนามกีฬาอำเภอทับสะแก",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unused",
    province: "ประจวบคีรีขันธ์",
    district: "อ.ทับสะแก",
    budget: 24480000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: 2561,
    progress: null,
    revived: false,
    photos: [],
    note: "สร้างเสร็จตั้งแต่ปี 2561 แต่หน่วยงานท้องถิ่นไม่สามารถรับโอนไปดูแลได้",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-25",
    name: "สนามกีฬาจังหวัดนราธิวาส",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unfinished",
    province: "นราธิวาส",
    district: "",
    budget: 385000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "บางส่วนก่อสร้างไม่เสร็จหลังผู้รับเหมาทิ้งงาน",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-26",
    name: "พุทธมณฑลจังหวัดสมุทรสาคร",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "abandoned",
    province: "สมุทรสาคร",
    district: "อ.บ้านแพ้ว",
    budget: 174000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "สร้างเสร็จแต่ขาดงบและหน่วยงานดูแลจนพื้นที่ทรุดโทรม",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-27",
    name: "ศูนย์กระจายสินค้าพืชพลังงานทดแทน",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unused",
    province: "สระแก้ว",
    district: "",
    budget: 49000000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "สร้างเสร็จแต่ใช้ไม่ได้เพราะติดปัญหาสิทธิการใช้ที่ดิน",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-28",
    name: "โรงงานแปรรูปผลิตภัณฑ์ยางพารา 8 แห่ง",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unused",
    province: "บึงกาฬ",
    district: "",
    budget: 194000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "สร้างแล้วแต่ติดปัญหาระบบไฟ ระบบบำบัดน้ำเสีย ที่ดิน และการบริหารทรัพย์สิน",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-29",
    name: "ท่าเรือบางโพ",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unused",
    province: "กรุงเทพมหานคร",
    district: "",
    budget: 44780000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "อาคารสร้างแล้วแต่พื้นที่บางส่วนไม่ได้เปิดใช้งานเต็มประโยชน์",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-30",
    name: "โครงการบ้านมั่นคงบางบัวทอง",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unfinished",
    province: "นนทบุรี",
    district: "อ.บางบัวทอง",
    budget: 20000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "งบที่เกี่ยวข้องราว 20 ล้านบาท โครงการก่อสร้างบ้านล่าช้าหลายปี",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-31",
    name: "โครงการสถานีตำรวจทดแทน 396 แห่งทั่วประเทศ",
    agency: "สำนักงานตำรวจแห่งชาติ",
    type: "ministry",
    status: "unfinished",
    province: null,
    district: "",
    budget: 5848000000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "สัญญารวม 5,848 ล้านบาท โครงการเดิมก่อสร้างไม่เสร็จตามสัญญา ก่อนต้องแก้ไขและก่อสร้างต่อเป็นรายแห่ง",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "none",
    verified: false,
  },
  {
    id: "C-32",
    name: "อาคารในเขตห้ามล่าสัตว์ป่าแหลมตะลุมพุก",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "abandoned",
    province: "นครศรีธรรมราช",
    district: "",
    budget: 5000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "มีรายงานว่าสร้างแล้วถูกปล่อยทิ้งร้าง",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-33",
    name: "สำนักงาน กกพ. แห่งใหม่ วิภาวดีรังสิต",
    agency: "สำนักงาน กกพ.",
    type: "autonomous",
    status: "unfinished",
    province: "กรุงเทพมหานคร",
    district: "",
    budget: 650000000,
    budgetApprox: true,
    yearStart: 2563,
    yearDue: 2567,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "เริ่มสร้างปี 2563 กำหนดเสร็จปี 2567 แต่ถึงปี 2569 ยังไม่เสร็จ หลังผู้รับเหมาหยุดงานและมีข้อพิพาทเรื่องสัญญา",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-34",
    name: "ศูนย์ราชการจังหวัดแพร่แห่งใหม่",
    agency: "จังหวัดแพร่",
    type: "ministry",
    status: "unfinished",
    province: "แพร่",
    district: "",
    budget: 657000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: 25,
    revived: false,
    photos: [],
    note: "ปี 2569 งานคืบหน้าเพียงราว 25% หลังหมดสัญญาและขยายเวลามาเกือบ 2 ปี ผู้รับเหมาขนอุปกรณ์ออกจากพื้นที่ อยู่ระหว่างดำเนินการเลิกสัญญา",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-35",
    name: "อาคารอำนวยการผู้ป่วยนอกและอุบัติเหตุฉุกเฉิน รพ.ตรัง",
    agency: "โรงพยาบาลตรัง",
    type: "hospital",
    status: "unfinished",
    province: "ตรัง",
    district: "",
    budget: 488100000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: true,
    photos: [],
    note: "สร้างมาราว 13 ปี เคยถูกผู้รับเหมาทิ้งงาน 3 ราย ปัจจุบันได้ผู้รับจ้างรอบใหม่และกลับมาก่อสร้างต่อแล้ว",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-36",
    name: "สำนักงานเขตลาดกระบังแห่งใหม่",
    agency: "กรุงเทพมหานคร",
    type: "local",
    status: "unfinished",
    province: "กรุงเทพมหานคร",
    district: "เขตลาดกระบัง",
    budget: 495000000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "อาคาร 9 ชั้น + ใต้ดิน 2 ชั้น โครงการล่าช้าและมีปัญหาผู้รับเหมาทิ้งงาน",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-37",
    name: "อาคารศูนย์สาธิตบริการและอาคารจอดรถ กรมควบคุมโรค",
    agency: "กรมควบคุมโรค",
    type: "ministry",
    status: "unfinished",
    province: null,
    district: "",
    budget: 607640000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: 2567,
    progress: null,
    revived: false,
    photos: [],
    note: "ก่อสร้างไม่เสร็จ กรมควบคุมโรคบอกเลิกสัญญาปลายปี 2567 เพราะงานล่าช้า",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "none",
    verified: false,
  },
  {
    id: "C-38",
    name: "อาคารศาลแขวงพระนครเหนือ และสถาบันพัฒนาข้าราชการฝ่ายตุลาการ",
    agency: "สำนักงานศาลยุติธรรม",
    type: "ministry",
    status: "unfinished",
    province: "กรุงเทพมหานคร",
    district: "",
    budget: 1377600000,
    budgetApprox: false,
    yearStart: null,
    yearDue: 2565,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "เลยกำหนดสัญญาตั้งแต่ปี 2565 แต่ยังไม่พร้อมใช้งานตามรายงานปี 2568",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-39",
    name: "อาคารศาลแพ่งพระโขนงและศาลอาญาพระโขนง",
    agency: "สำนักงานศาลยุติธรรม",
    type: "ministry",
    status: "unused",
    province: "กรุงเทพมหานคร",
    district: "",
    budget: 304740000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "เคยตรวจรับแล้วทั้งที่ใช้งานไม่ได้เต็มรูปแบบ ห้องพิจารณาคดีสร้างเสร็จเพียง 1 ห้องจากประมาณ 39 ห้อง และลิฟต์ใช้ได้ 1 ชุดจาก 7 ชุด",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-40",
    name: "อาคารผู้ป่วยนอก 9 ชั้น รพ.สุราษฎร์ธานี",
    agency: "โรงพยาบาลสุราษฎร์ธานี",
    type: "hospital",
    status: "unfinished",
    province: "สุราษฎร์ธานี",
    district: "",
    budget: 523000000,
    budgetApprox: true,
    yearStart: 2559,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ก่อสร้างตั้งแต่ปี 2559 แต่ล่าช้าหลายปีและต้องยกเลิกสัญญาผู้รับเหมารายเดิม",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-41",
    name: "อาคาร รพ.ห้วยยอด",
    agency: "โรงพยาบาลห้วยยอด",
    type: "hospital",
    status: "unfinished",
    province: "ตรัง",
    district: "อ.ห้วยยอด",
    budget: 140000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "รายงานปี 2568 ระบุว่าก่อสร้างมาหลายปีแต่ยังไม่เสร็จ",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-42",
    name: "อาคารเรียนและห้องปฏิบัติการวิชาชีพ คณะเทคโนโลยีอุตสาหกรรม มรภ.นครศรีธรรมราช",
    agency: "มหาวิทยาลัยราชภัฏนครศรีธรรมราช",
    type: "school",
    status: "unfinished",
    province: "นครศรีธรรมราช",
    district: "",
    budget: 90000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "เคยถูกรายงานว่าสร้างค้างหลายปี",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-43",
    name: "อัฒจันทร์สนามกีฬา มรภ.นครศรีธรรมราช",
    agency: "มหาวิทยาลัยราชภัฏนครศรีธรรมราช",
    type: "school",
    status: "unused",
    province: "นครศรีธรรมราช",
    district: "",
    budget: 42000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "สร้างเสร็จแต่มีปัญหาโครงสร้างหลังคา ต้องใช้เหล็กค้ำและไม่สามารถใช้งานได้ตามปกติ (สถานะรายงานปี 2565)",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-44",
    name: "สนามกีฬาแห่งชาติภาคตะวันออก เมืองพัทยา",
    agency: "เมืองพัทยา",
    type: "local",
    status: "unfinished",
    province: "ชลบุรี",
    district: "เมืองพัทยา",
    budget: 774000000,
    budgetApprox: false,
    yearStart: 2551,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "เริ่มตั้งแต่ปี 2551 มีปัญหาผู้รับเหมาทิ้งงานและก่อสร้างยืดเยื้อ (สถานะรายงานปี 2565)",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-45",
    name: "สนามกีฬาสมุทรปราการ เคหะเมืองใหม่บางพลี",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unfinished",
    province: "สมุทรปราการ",
    district: "อ.บางพลี",
    budget: 160000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ทั้งสระว่ายน้ำ สนามเทนนิสและโรงยิม มีปัญหาก่อสร้าง/ใช้งานไม่ได้ (สถานะรายงานปี 2565)",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-46",
    name: "หมู่บ้านวิถีไทยในจารึก",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unused",
    province: "สุโขทัย",
    district: "",
    budget: 350000000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "สร้างเป็นศูนย์นักท่องเที่ยว ศูนย์สาธิต ร้าน OTOP ฯลฯ แต่รายงานปี 2565 ระบุว่ากว่า 10 ปียังไม่เคยเปิดใช้งาน",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-47",
    name: "ตลาดอินโดจีน มุกดาหาร",
    agency: "จังหวัดมุกดาหาร",
    type: "ministry",
    status: "unfinished",
    province: "มุกดาหาร",
    district: "",
    budget: 149950000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: 2565,
    progress: null,
    revived: false,
    photos: [],
    note: "โครงการปรับปรุง 149.95 ล้านบาท งานล่าช้าหลายปีจนจังหวัดบอกเลิกสัญญาผู้รับเหมาในปี 2565",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-48",
    name: "ศูนย์เรียนรู้และแปรรูปปลาสลิด คลองด่าน",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "abandoned",
    province: "สมุทรปราการ",
    district: "",
    budget: 25080000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: 2560,
    progress: null,
    revived: false,
    photos: [],
    note: "มูลค่าสิ่งก่อสร้างและครุภัณฑ์ราว 25.08 ล้านบาท เปิดใช้งานครั้งแรกปี 2560 แล้วแทบไม่ได้ใช้อีก (สถานะรายงานปี 2565)",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-49",
    name: "ศูนย์จำหน่ายสินค้าชุมชนและจุดพักรถ ยางตลาด",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unused",
    province: "กาฬสินธุ์",
    district: "อ.ยางตลาด",
    budget: 19000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "สร้างแล้วมีปัญหาไม่สามารถใช้ประโยชน์ตามแผน (สถานะรายงานปี 2565)",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-50",
    name: "ตลาดสินค้าเกษตรและ OTOP ทุ่งกระต่ายขัง",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "abandoned",
    province: "ประจวบคีรีขันธ์",
    district: "",
    budget: 20000000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "สร้างเป็นจุดพักและจำหน่ายสินค้า แต่กลายเป็นตลาดร้าง (สถานะรายงานปี 2565)",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-51",
    name: "ม่อนเสาหินพิศวง",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "abandoned",
    province: "แพร่",
    district: "",
    budget: 9300000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "มีศูนย์บริการนักท่องเที่ยว อาคาร OTOP และศาลาที่พัก แต่เคยถูกปล่อยร้างและบางส่วนสร้างไม่เสร็จ",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-52",
    name: "เตาเผาขยะ ตำบลเทพราช อำเภอสิชล",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "local",
    status: "unused",
    province: "นครศรีธรรมราช",
    district: "อ.สิชล",
    budget: 8970000,
    budgetApprox: false,
    yearStart: 2556,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "สร้างตั้งแต่ปี 2556 แต่รายงานปี 2565 ระบุว่าไม่เคยใช้งาน",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-53",
    name: "ศูนย์พัฒนาคุณภาพชีวิตและส่งเสริมอาชีพผู้สูงอายุ ตำบลท่านา",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "local",
    status: "unused",
    province: "พังงา",
    district: "",
    budget: null,
    budgetApprox: false,
    yearStart: 2559,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "สร้างปี 2559 แต่รายงานปี 2565 ระบุว่าสร้างเสร็จแล้วไม่ได้เปิดใช้งาน",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-54",
    name: "ศูนย์เรียนรู้เศรษฐกิจฐานรากวิถีชุมชน ตำบลช่อง",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "abandoned",
    province: "ตรัง",
    district: "",
    budget: null,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "มีทั้งอาคาร ตลาด และสนามเด็กเล่น ถูกปล่อยร้างมากกว่า 5 ปีตามข้อมูลปี 2565",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-55",
    name: "อาคารทิ้งร้างหลายหลัง วิทยาลัยเกษตรและเทคโนโลยีตรัง",
    agency: "วิทยาลัยเกษตรและเทคโนโลยีตรัง",
    type: "school",
    status: "abandoned",
    province: "ตรัง",
    district: "",
    budget: null,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "สร้างเป็นอาคารพัก/ใช้งานภายในวิทยาลัย แต่มีหลายหลังไม่ได้ใช้งานและทรุดโทรมตามการสำรวจปี 2565",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },];

// จุดอ้างอิงกลางจังหวัด ใช้วางวงจำนวนบนแผนที่เท่านั้น ไม่ใช่ตำแหน่งอาคาร
const PROVINCE_ANCHOR = {
  "กรุงเทพมหานคร": [13.7711, 100.6209],
  "กาฬสินธุ์": [16.6324, 103.6277],
  "ชลบุรี": [13.1973, 101.209],
  "ชุมพร": [10.3672, 99.0707],
  "ตรัง": [7.5283, 99.616],
  "ตาก": [16.6962, 98.7962],
  "นครพนม": [17.372, 104.4347],
  "นครราชสีมา": [14.9576, 102.1163],
  "นครศรีธรรมราช": [8.3723, 99.7791],
  "นนทบุรี": [13.9262, 100.3892],
  "นราธิวาส": [6.1722, 101.7226],
  "บึงกาฬ": [18.145, 103.721],
  "ประจวบคีรีขันธ์": [11.9207, 99.6269],
  "พะเยา": [19.2274, 100.1854],
  "พังงา": [8.6802, 98.4247],
  "มุกดาหาร": [16.5577, 104.524],
  "ยะลา": [6.1838, 101.2257],
  "ระยอง": [12.8508, 101.4229],
  "ร้อยเอ็ด": [15.9233, 103.8275],
  "สงขลา": [6.8051, 100.5827],
  "สมุทรปราการ": [13.5979, 100.7042],
  "สมุทรสาคร": [13.5717, 100.2158],
  "สระแก้ว": [13.7787, 102.2948],
  "สุพรรณบุรี": [14.6087, 99.8969],
  "สุราษฎร์ธานี": [9.0322, 99.063],
  "สุโขทัย": [17.2466, 99.6978],
  "อำนาจเจริญ": [15.8716, 104.7688],
  "อุดรธานี": [17.426, 102.855],
  "แพร่": [18.1955, 100.0648],};

const STATUS = {
  unfinished: { th: 'สร้างไม่เสร็จ', desc: 'ก่อสร้างค้าง ไม่เคยแล้วเสร็จ' },
  abandoned:  { th: 'ทิ้งร้าง',      desc: 'เคยใช้งาน แล้วถูกปล่อยร้าง' },
  unused:     { th: 'เสร็จแต่ไม่ใช้', desc: 'สร้างเสร็จ แต่ไม่เคยเปิดใช้เต็มที่' },
};

const AGENCY_TYPES = {
  ministry:   'ส่วนราชการ',
  autonomous: 'องค์กรอิสระ / องค์การมหาชน',
  school:     'สถานศึกษา',
  hospital:   'โรงพยาบาล',
  local:      'องค์กรปกครองส่วนท้องถิ่น',
  soe:        'รัฐวิสาหกิจ',
  unknown:    'ไม่ระบุในข้อมูลต้นทาง',
};

const REGION_NAMES = {
  north: 'เหนือ', northeast: 'อีสาน', central: 'กลาง',
  west: 'ตะวันตก', east: 'ตะวันออก', south: 'ใต้',
};
