// ─────────────────────────────────────────────────────────────────────────────
// อาคารและโครงการรัฐที่สร้างค้าง ทิ้งร้าง หรือสร้างเสร็จแต่ใช้ประโยชน์ไม่ได้
//
// ที่มา: คอมเมนต์ในโพสต์ของ Nat Luengnaruemitchai ที่ขอรูปและพิกัดตึกราชการ
// ที่ร้างหรือสร้างไม่เสร็จ เพื่อทำ "รายการเที่ยวตึกร้างทั่วไทย" (17 ก.ย. 2569)
// ปรับปรุงเป็นชุด 64 รายการเมื่อ 19 ก.ย. 2569
//
// ⚠ ทุกรายการยังเป็นข้อมูลบอกต่อ ยังไม่ได้ตรวจสอบกับเอกสารราชการ (verified: false)
// ⚠ ยังไม่มีรายการไหนมีพิกัดจริง — lat/lng เป็น null ทุกแถว ตำแหน่งบนแผนที่
//   แสดงได้แค่ระดับจังหวัด (precision: 'province')
//
// ── โครงสร้างหนึ่งรายการ ──────────────────────────────────────────────────────
// id           string   รหัสอ้างอิง
// group        string   building (อาคาร) | infrastructure (โครงสร้างพื้นฐาน)
// name         string   ชื่ออาคาร/โครงการ
// agency       string   หน่วยงานเจ้าของโครงการ
// type         string   ministry | local | hospital | school | soe | autonomous | unknown
// status       string   unfinished (สร้างไม่เสร็จ) | abandoned (ทิ้งร้าง) | unused (เสร็จแต่ไม่ใช้)
// province     string   ชื่อจังหวัดไทย ต้องตรงกับ provinces.js — null = ไม่ระบุ/ทั่วประเทศ
// district     string   อำเภอ/เขต ('' ถ้าไม่ระบุ)
// budget       number   งบประมาณ หน่วยบาท (null = ไม่ระบุ)
// budgetApprox boolean  true = ต้นทางใช้คำว่า "ราว/กว่า/เกือบ" ตัวเลขไม่ตายตัว
// yearStart    number   ปี พ.ศ. ที่เริ่มก่อสร้าง
// yearDue      number   ปี พ.ศ. ที่ต้องแล้วเสร็จตามสัญญา
// yearStalled  number   ปี พ.ศ. ที่หยุดงาน / เริ่มไม่ได้ใช้
// progress     number   % ความคืบหน้าที่ต้นทางระบุ
// revived      boolean  true = กลับมาก่อสร้างต่อแล้ว
// photos       array    URL รูป (relative หรือ absolute) หรือ data URI
// note         string   ข้อความจากต้นทาง (เก็บคำเดิมไว้ ไม่ตีความเพิ่ม)
// source       string   แหล่งที่มา
// sourceUrl    string   ลิงก์อ้างอิง
// lat, lng     number   พิกัด WGS84 — null จนกว่าจะมีคนส่งพิกัดจริงมา
// precision    string   'exact' = พิกัดจริง | 'province' = รู้แค่จังหวัด | 'none' = ไม่รู้ตำแหน่ง
// verified     boolean  true = ตรวจสอบกับเอกสาร/ภาพถ่ายแล้ว
// ─────────────────────────────────────────────────────────────────────────────

const BUILDINGS = [
  {
    id: "C-01",
    group: "building",
    name: "สำนักงาน กสทช. แห่งใหม่",
    agency: "สำนักงาน กสทช.",
    type: "autonomous",
    status: "unfinished",
    province: "นนทบุรี",
    district: "",
    budget: 2643000000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: 76,
    revived: false,
    photos: [],
    note: "งานค้างหลังยกเลิกสัญญาเดิม",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-02",
    group: "building",
    name: "อาคารสำนักงบประมาณแห่งใหม่",
    agency: "สำนักงบประมาณ",
    type: "ministry",
    status: "unfinished",
    province: "กรุงเทพมหานคร",
    district: "",
    budget: 2100000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "โครงการราว 2,100 ลบ. เปิดใช้บางส่วน งานบางส่วนยังไม่สมบูรณ์",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-03",
    group: "building",
    name: "อควาเรียมหอยสังข์",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unused",
    province: "สงขลา",
    district: "",
    budget: 1400000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ใช้งบแล้วกว่า 1,400 ลบ. ค้างมาราว 18 ปี",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-04",
    group: "building",
    name: "สถาบันพัฒนาข้าราชการฝ่ายตุลาการ ปากช่อง",
    agency: "สำนักงานศาลยุติธรรม",
    type: "ministry",
    status: "unfinished",
    province: "นครราชสีมา",
    district: "อ.ปากช่อง",
    budget: 782800000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ก่อสร้างล่าช้า",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-05",
    group: "building",
    name: "ศาลแพ่งและศาลอาญามีนบุรี",
    agency: "สำนักงานศาลยุติธรรม",
    type: "ministry",
    status: "unfinished",
    province: "กรุงเทพมหานคร",
    district: "เขตมีนบุรี",
    budget: 782000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: 33,
    revived: false,
    photos: [],
    note: "งานได้ราวหนึ่งในสามก่อนเลิกสัญญา",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-06",
    group: "building",
    name: "ศาลอุทธรณ์ภาค 5 และที่พัก",
    agency: "สำนักงานศาลยุติธรรม",
    type: "ministry",
    status: "unfinished",
    province: "เชียงราย",
    district: "",
    budget: 737300000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "สัญญาเดิม 737.3 ลบ. งานค้าง ต้องประมูลงานส่วนที่เหลือใหม่",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-07",
    group: "building",
    name: "บ้านพักตุลาการ “บ้านป่าแหว่ง”",
    agency: "สำนักงานศาลยุติธรรม",
    type: "ministry",
    status: "unused",
    province: "เชียงใหม่",
    district: "",
    budget: null,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "อาคารจำนวนมากไม่ได้ใช้งานและถูกส่งคืนกรมธนารักษ์",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-08",
    group: "building",
    name: "ศาลแขวงพระนครเหนือและสถาบันพัฒนาข้าราชการฝ่ายตุลาการ",
    agency: "สำนักงานศาลยุติธรรม",
    type: "ministry",
    status: "unfinished",
    province: "กรุงเทพมหานคร",
    district: "",
    budget: 1377600000,
    budgetApprox: false,
    yearStart: null,
    yearDue: 2565,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ล่าช้าหลายปี",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-09",
    group: "building",
    name: "ศาลแพ่งและศาลอาญาพระโขนง",
    agency: "สำนักงานศาลยุติธรรม",
    type: "ministry",
    status: "unused",
    province: "กรุงเทพมหานคร",
    district: "",
    budget: 304700000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "เคยมีปัญหางานไม่พร้อมใช้งานครบถ้วน",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-10",
    group: "building",
    name: "สำนักงาน กกพ. แห่งใหม่",
    agency: "สำนักงาน กกพ.",
    type: "autonomous",
    status: "unfinished",
    province: "กรุงเทพมหานคร",
    district: "",
    budget: 650000000,
    budgetApprox: true,
    yearStart: 2563,
    yearDue: 2567,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ก่อสร้างล่าช้า/หยุดชะงัก",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-11",
    group: "building",
    name: "ศูนย์ราชการจังหวัดแพร่แห่งใหม่",
    agency: "จังหวัดแพร่",
    type: "ministry",
    status: "unfinished",
    province: "แพร่",
    district: "",
    budget: 657000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: 25,
    revived: false,
    photos: [],
    note: "กว่า 657 ลบ. งานล่าช้าหนัก",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-12",
    group: "building",
    name: "อาคารศูนย์สาธิตบริการและอาคารจอดรถ กรมควบคุมโรค",
    agency: "กรมควบคุมโรค",
    type: "ministry",
    status: "unfinished",
    province: null,
    district: "",
    budget: 499900000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: 2567,
    progress: null,
    revived: false,
    photos: [],
    note: "สัญญาเดิม 480 ลบ. ถูกยกเลิก ก่อนจ้างงานส่วนที่เหลือใหม่ 499.9 ลบ.",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "none",
    verified: false,
  },
  {
    id: "C-13",
    group: "building",
    name: "อาคารผู้ป่วยนอกและอุบัติเหตุ รพ.สงขลา",
    agency: "โรงพยาบาลสงขลา",
    type: "hospital",
    status: "unfinished",
    province: "สงขลา",
    district: "",
    budget: 420000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "กว่า 420 ลบ. สัญญาเดิมถูกยกเลิก ต้องประมูลต่อ",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-14",
    group: "building",
    name: "อาคารอำนวยการผู้ป่วยนอกและฉุกเฉิน รพ.ตรัง",
    agency: "โรงพยาบาลตรัง",
    type: "hospital",
    status: "unfinished",
    province: "ตรัง",
    district: "",
    budget: 488100000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: true,
    photos: [],
    note: "เคยถูกทิ้งงานหลายครั้ง ต่อมาได้ผู้รับจ้างรอบใหม่และกลับมาก่อสร้างต่อ",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-15",
    group: "building",
    name: "อาคารผู้ป่วยนอก รพ.สุราษฎร์ธานี",
    agency: "โรงพยาบาลสุราษฎร์ธานี",
    type: "hospital",
    status: "unfinished",
    province: "สุราษฎร์ธานี",
    district: "",
    budget: 523000000,
    budgetApprox: true,
    yearStart: 2559,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ก่อสร้างล่าช้าหลายปี",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-16",
    group: "building",
    name: "อาคาร รพ.ห้วยยอด",
    agency: "โรงพยาบาลห้วยยอด",
    type: "hospital",
    status: "unfinished",
    province: "ตรัง",
    district: "อ.ห้วยยอด",
    budget: 140000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ก่อสร้างค้าง",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-17",
    group: "building",
    name: "สำนักงาน ป.ป.ช. ภาค 9 และ ป.ป.ช.สงขลา",
    agency: "สำนักงาน ป.ป.ช.",
    type: "autonomous",
    status: "unfinished",
    province: "สงขลา",
    district: "",
    budget: 40000000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "สัญญาเดิม 40 ลบ. ผู้รับเหมาทิ้งงาน",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-18",
    group: "building",
    name: "สำนักงาน สตง. พะเยา",
    agency: "สำนักงานการตรวจเงินแผ่นดิน",
    type: "autonomous",
    status: "unfinished",
    province: "พะเยา",
    district: "",
    budget: 70000000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ผู้รับเหมาทิ้งงาน",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-19",
    group: "building",
    name: "สำนักงาน สตง. ร้อยเอ็ด",
    agency: "สำนักงานการตรวจเงินแผ่นดิน",
    type: "autonomous",
    status: "unfinished",
    province: "ร้อยเอ็ด",
    district: "",
    budget: 58490000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "งานค้างและเลิกสัญญา",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-20",
    group: "building",
    name: "สำนักงาน สตง. ตาก",
    agency: "สำนักงานการตรวจเงินแผ่นดิน",
    type: "autonomous",
    status: "unfinished",
    province: "ตาก",
    district: "",
    budget: 46900000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ผู้รับเหมาทิ้งงาน",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-21",
    group: "building",
    name: "สถานกักกันวัยหนุ่มนครศรีธรรมราช",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "ministry",
    status: "unfinished",
    province: "นครศรีธรรมราช",
    district: "",
    budget: 224000000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "อาคารก่อสร้างไม่แล้วเสร็จ ไซต์หยุดนิ่ง",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-22",
    group: "building",
    name: "สถานีดับเพลิงและกู้ภัยพระโขนง",
    agency: "กรุงเทพมหานคร",
    type: "local",
    status: "unfinished",
    province: "กรุงเทพมหานคร",
    district: "เขตพระโขนง",
    budget: 148940000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ล่าช้าหลายปี ยังไม่พร้อมใช้งาน",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-23",
    group: "building",
    name: "สำนักงานเขตลาดกระบังแห่งใหม่",
    agency: "กรุงเทพมหานคร",
    type: "local",
    status: "unfinished",
    province: "กรุงเทพมหานคร",
    district: "เขตลาดกระบัง",
    budget: 495000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ก่อสร้างล่าช้า",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-24",
    group: "building",
    name: "สถานีขนส่งนครสวรรค์ แห่งที่ 2",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unused",
    province: "นครสวรรค์",
    district: "",
    budget: 42000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "กว่า 42 ลบ. สร้างเสร็จแต่ไม่เคยเปิดใช้เป็นสถานีขนส่งเกือบ 20 ปี",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-25",
    group: "building",
    name: "อาคารเรียน รร.วัดสุทธิวราราม",
    agency: "โรงเรียนวัดสุทธิวราราม",
    type: "school",
    status: "unfinished",
    province: "กรุงเทพมหานคร",
    district: "",
    budget: 37380000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "งานล่าช้า/ค้าง",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-26",
    group: "building",
    name: "อาคารเรียน รร.อนุบาลเชิงเนิน",
    agency: "โรงเรียนอนุบาลเชิงเนิน",
    type: "school",
    status: "unused",
    province: "ระยอง",
    district: "",
    budget: 32040000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "สร้างแล้วไม่ได้ใช้หลายปี",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-27",
    group: "building",
    name: "อาคารเรียน รร.อนุบาลหัวตะพาน",
    agency: "โรงเรียนอนุบาลหัวตะพาน",
    type: "school",
    status: "unfinished",
    province: "อำนาจเจริญ",
    district: "อ.หัวตะพาน",
    budget: 17840000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ก่อสร้างค้าง",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-28",
    group: "building",
    name: "อาคารเรียน รร.เทศบาลบ้านคลองภาษี",
    agency: "โรงเรียนเทศบาลบ้านคลองภาษี",
    type: "school",
    status: "unfinished",
    province: "ตรัง",
    district: "",
    budget: null,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ผู้รับเหมาทิ้งงาน",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-29",
    group: "building",
    name: "อาคารอเนกประสงค์ 6 ชั้น รร.เทศบาล 2",
    agency: "โรงเรียนเทศบาล 2 วัดกะพังสุรินทร์",
    type: "school",
    status: "unfinished",
    province: "ตรัง",
    district: "",
    budget: 72240000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "สัญญาเดิม 72.24 ลบ. สร้างได้ประมาณ 3 ชั้นก่อนหยุด",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-30",
    group: "building",
    name: "อาคารเรียนและห้องปฏิบัติการ มรภ.นครศรีธรรมราช",
    agency: "มหาวิทยาลัยราชภัฏนครศรีธรรมราช",
    type: "school",
    status: "unfinished",
    province: "นครศรีธรรมราช",
    district: "",
    budget: 90000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ก่อสร้างค้าง",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-31",
    group: "building",
    name: "อัฒจันทร์สนามกีฬา มรภ.นครศรีธรรมราช",
    agency: "มหาวิทยาลัยราชภัฏนครศรีธรรมราช",
    type: "school",
    status: "unused",
    province: "นครศรีธรรมราช",
    district: "",
    budget: 42000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "มีปัญหาโครงสร้างและการใช้งาน",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-32",
    group: "building",
    name: "Korat Living Library",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unused",
    province: "นครราชสีมา",
    district: "",
    budget: 90000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "เกือบ 90 ลบ. สร้างเสร็จแต่ไม่ได้เปิดใช้งานจริงมานานกว่า 10 ปี",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-33",
    group: "building",
    name: "ศูนย์ดาราศาสตร์เฉลิมพระเกียรติ 7 รอบ โคราช",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "abandoned",
    province: "นครราชสีมา",
    district: "",
    budget: 155700000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "งบก่อสร้างเริ่มต้น 155.7 ลบ. ปิดใช้งานและเตรียมฟื้นฟูใหม่",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-34",
    group: "building",
    name: "พิพิธภัณฑ์องค์ความรู้เรื่องไม้มีค่า",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unfinished",
    province: "กรุงเทพมหานคร",
    district: "เขตวังทองหลาง",
    budget: 1045000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: true,
    photos: [],
    note: "ระยะ 1 ราว 1,045 ลบ. ก่อสร้างยืดเยื้อ ยังสร้างต่ออยู่",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-35",
    group: "building",
    name: "ศูนย์แสดงศิลปวัฒนธรรมพระยารัษฎานุประดิษฐ์",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unfinished",
    province: "ตรัง",
    district: "",
    budget: 107000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ใช้งบเดิมราว 107 ลบ. ค้างมาหลายปี",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-36",
    group: "building",
    name: "ศูนย์ OTOP หนองญาติ",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unused",
    province: "นครพนม",
    district: "",
    budget: 30000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "กว่า 30 ลบ. สร้างแล้วไม่เคยใช้งานจริงราว 20 ปี",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-37",
    group: "building",
    name: "ศูนย์ OTOP สุไหงโก-ลก",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unused",
    province: "นราธิวาส",
    district: "อ.สุไหงโก-ลก",
    budget: 49000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "อาคารบางส่วนไม่ได้ใช้และชำรุด",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-38",
    group: "building",
    name: "ศูนย์ส่งเสริมอาชีพการนวด เบตง",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "abandoned",
    province: "ยะลา",
    district: "อ.เบตง",
    budget: 16000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "สร้างแล้วถูกปล่อยร้าง",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-39",
    group: "building",
    name: "ศูนย์ส่งเสริมการท่องเที่ยวคลองท่าเสม็ด",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unused",
    province: "ชุมพร",
    district: "",
    budget: 19780000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "สร้างเสร็จแต่ยังใช้ประโยชน์ไม่เต็มที่",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-40",
    group: "building",
    name: "ศูนย์พัฒนาเด็กเล็ก บ้านธาตุ",
    agency: "เทศบาลตำบลบ้านธาตุ",
    type: "local",
    status: "unused",
    province: "อุดรธานี",
    district: "",
    budget: 1495000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: 2558,
    progress: null,
    revived: false,
    photos: [],
    note: "สร้างเสร็จแต่ไม่ได้ใช้งานหลายปี",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-41",
    group: "building",
    name: "บ้านพักเด็กและครอบครัว นครศรีธรรมราช",
    agency: "บ้านพักเด็กและครอบครัว",
    type: "ministry",
    status: "abandoned",
    province: "นครศรีธรรมราช",
    district: "",
    budget: null,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ถูกระบุในชุดข้อมูลอาคารรัฐรอทบทวน/ทิ้งร้าง",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-42",
    group: "building",
    name: "ศูนย์เรียนรู้และแปรรูปปลาสลิด คลองด่าน",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "abandoned",
    province: "สมุทรปราการ",
    district: "",
    budget: 25000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: 2560,
    progress: null,
    revived: false,
    photos: [],
    note: "เปิดใช้ช่วงสั้นแล้วแทบไม่ได้ใช้งาน",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-43",
    group: "building",
    name: "ศูนย์จำหน่ายสินค้าชุมชนและจุดพักรถ ยางตลาด",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unused",
    province: "กาฬสินธุ์",
    district: "อ.ยางตลาด",
    budget: 19000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ใช้ประโยชน์ไม่ได้ตามแผน",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-44",
    group: "building",
    name: "ตลาดสินค้าเกษตรและ OTOP ทุ่งกระต่ายขัง",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "abandoned",
    province: "ประจวบคีรีขันธ์",
    district: "",
    budget: 20000000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "กลายเป็นตลาดร้าง",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-45",
    group: "building",
    name: "ศูนย์พัฒนาคุณภาพชีวิตผู้สูงอายุ ต.ท่านา",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "local",
    status: "unused",
    province: "พังงา",
    district: "",
    budget: null,
    budgetApprox: false,
    yearStart: 2559,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "สร้างเสร็จแต่ไม่ได้เปิดใช้",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-46",
    group: "building",
    name: "ศูนย์เรียนรู้เศรษฐกิจฐานราก ต.ช่อง",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "abandoned",
    province: "ตรัง",
    district: "",
    budget: null,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "อาคารและตลาดถูกปล่อยร้างหลายปี",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-47",
    group: "building",
    name: "อาคารหลายหลัง วิทยาลัยเกษตรและเทคโนโลยีตรัง",
    agency: "วิทยาลัยเกษตรและเทคโนโลยีตรัง",
    type: "school",
    status: "abandoned",
    province: "ตรัง",
    district: "",
    budget: null,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ไม่ได้ใช้งานและทรุดโทรม",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-48",
    group: "building",
    name: "ม่อนเสาหินพิศวง",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "abandoned",
    province: "แพร่",
    district: "",
    budget: 9300000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "สิ่งก่อสร้างบางส่วนร้าง/ไม่เสร็จ",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-49",
    group: "building",
    name: "หมู่บ้านวิถีไทยในจารึก",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unused",
    province: "สุโขทัย",
    district: "",
    budget: 350000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "สร้างแล้วไม่ได้เปิดใช้งานเป็นเวลานาน",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-50",
    group: "building",
    name: "พุทธมณฑลจังหวัดสมุทรสาคร",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "abandoned",
    province: "สมุทรสาคร",
    district: "อ.บ้านแพ้ว",
    budget: 174000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ขาดงบและผู้ดูแลจนทรุดโทรม",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-51",
    group: "building",
    name: "สนามกีฬาอำเภออู่ทอง",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unused",
    province: "สุพรรณบุรี",
    district: "อ.อู่ทอง",
    budget: null,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "สร้างเสร็จแต่ไม่ได้เปิดใช้งานเป็นเวลานาน",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-52",
    group: "building",
    name: "สนามกีฬาอำเภอทับสะแก",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unused",
    province: "ประจวบคีรีขันธ์",
    district: "อ.ทับสะแก",
    budget: 24480000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: 2561,
    progress: null,
    revived: false,
    photos: [],
    note: "สร้างเสร็จแต่ท้องถิ่นรับโอนไม่ได้",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-53",
    group: "building",
    name: "สนามกีฬาจังหวัดนราธิวาส",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unfinished",
    province: "นราธิวาส",
    district: "",
    budget: 385000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "งานบางส่วนค้างหลังผู้รับเหมาทิ้งงาน",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-54",
    group: "building",
    name: "สนามกีฬาแห่งชาติภาคตะวันออก พัทยา",
    agency: "เมืองพัทยา",
    type: "local",
    status: "unfinished",
    province: "ชลบุรี",
    district: "เมืองพัทยา",
    budget: 774000000,
    budgetApprox: true,
    yearStart: 2551,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ก่อสร้างยืดเยื้อมานาน",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-55",
    group: "building",
    name: "สนามกีฬาสมุทรปราการ เคหะเมืองใหม่บางพลี",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unfinished",
    province: "สมุทรปราการ",
    district: "อ.บางพลี",
    budget: 160000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "โครงการราว 160 ลบ. มีส่วนที่ใช้งานไม่ได้",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-56",
    group: "building",
    name: "ท่าเรือบางโพ",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unused",
    province: "กรุงเทพมหานคร",
    district: "",
    budget: 44780000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "พื้นที่บางส่วนไม่ได้ใช้เต็มประโยชน์",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-57",
    group: "building",
    name: "ศูนย์กระจายสินค้าพืชพลังงานทดแทน",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unused",
    province: "สระแก้ว",
    district: "",
    budget: 49000000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "สร้างเสร็จแต่ติดปัญหาสิทธิใช้ที่ดิน",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-58",
    group: "building",
    name: "โรงงานแปรรูปยางพารา 8 แห่ง",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unused",
    province: "บึงกาฬ",
    district: "",
    budget: 194000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ติดปัญหาที่ดิน ไฟฟ้า บำบัดน้ำเสีย และการบริหาร",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-59",
    group: "building",
    name: "โครงการบ้านมั่นคงบางบัวทอง",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unfinished",
    province: "นนทบุรี",
    district: "อ.บางบัวทอง",
    budget: 20000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "งบเกี่ยวข้องราว 20 ลบ. โครงการก่อสร้างล่าช้าหลายปี",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-60",
    group: "building",
    name: "อาคารในเขตห้ามล่าสัตว์ป่าแหลมตะลุมพุก",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "abandoned",
    province: "นครศรีธรรมราช",
    district: "",
    budget: 5000000,
    budgetApprox: true,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "สร้างแล้วถูกปล่อยร้าง",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-61",
    group: "building",
    name: "โครงการสถานีตำรวจทดแทน 396 แห่ง",
    agency: "สำนักงานตำรวจแห่งชาติ",
    type: "ministry",
    status: "unfinished",
    province: null,
    district: "",
    budget: 5848000000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "สัญญาเดิม 5,848 ลบ. โครงการเดิมสร้างไม่เสร็จ ก่อนทยอยแก้ไขเป็นรายแห่ง",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "none",
    verified: false,
  },
  {
    id: "C-62",
    group: "infrastructure",
    name: "โครงการจัดหาน้ำบาดาลขนาดใหญ่ บ้านสะง้อ",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unused",
    province: "บึงกาฬ",
    district: "",
    budget: 85340000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "สร้างแล้วพบปัญหาระบบจ่ายน้ำ เครื่องสูบน้ำ และการบริหารหลังส่งมอบ",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-63",
    group: "infrastructure",
    name: "โครงการปรับปรุงระบบส่งน้ำ จ.พังงา",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "unknown",
    status: "unused",
    province: "พังงา",
    district: "",
    budget: 15939000,
    budgetApprox: false,
    yearStart: null,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "ระบบยาวกว่า 8.6 กม. มีข้อสงสัยเรื่องความสมบูรณ์และการใช้งาน",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },
  {
    id: "C-64",
    group: "infrastructure",
    name: "เตาเผาขยะ ต.เทพราช อ.สิชล",
    agency: "ไม่ระบุในข้อมูลต้นทาง",
    type: "local",
    status: "unused",
    province: "นครศรีธรรมราช",
    district: "อ.สิชล",
    budget: 8970000,
    budgetApprox: false,
    yearStart: 2556,
    yearDue: null,
    yearStalled: null,
    progress: null,
    revived: false,
    photos: [],
    note: "มีรายงานว่าสร้างแล้วไม่เคยใช้งาน",
    source: "คอมเมนต์ในโพสต์ต้นทาง",
    sourceUrl: "",
    lat: null,
    lng: null,
    precision: "province",
    verified: false,
  },];

// จุดอ้างอิงกลางจังหวัด ใช้วางวงจำนวนบนแผนที่เท่านั้น ไม่ใช่ตำแหน่งอาคาร
const PROVINCE_ANCHOR = {
  "กรุงเทพมหานคร": [13.7711, 100.6209],
  "กาฬสินธุ์": [16.6324, 103.6277],
  "ชลบุรี": [13.1973, 101.209],
  "ชุมพร": [10.3672, 99.0707],
  "ตรัง": [7.5283, 99.616],
  "ตาก": [16.6962, 98.7962],
  "นครพนม": [17.372, 104.4347],
  "นครราชสีมา": [14.9576, 102.1163],
  "นครศรีธรรมราช": [8.3723, 99.7791],
  "นครสวรรค์": [15.692, 100.1334],
  "นนทบุรี": [13.9262, 100.3892],
  "นราธิวาส": [6.1722, 101.7226],
  "บึงกาฬ": [18.145, 103.721],
  "ประจวบคีรีขันธ์": [11.9207, 99.6269],
  "พะเยา": [19.2274, 100.1854],
  "พังงา": [8.6802, 98.4247],
  "ยะลา": [6.1838, 101.2257],
  "ระยอง": [12.8508, 101.4229],
  "ร้อยเอ็ด": [15.9233, 103.8275],
  "สงขลา": [6.8051, 100.5827],
  "สมุทรปราการ": [13.5979, 100.7042],
  "สมุทรสาคร": [13.5717, 100.2158],
  "สระแก้ว": [13.7787, 102.2948],
  "สุพรรณบุรี": [14.6087, 99.8969],
  "สุราษฎร์ธานี": [9.0322, 99.063],
  "สุโขทัย": [17.2466, 99.6978],
  "อำนาจเจริญ": [15.8716, 104.7688],
  "อุดรธานี": [17.426, 102.855],
  "เชียงราย": [19.8444, 99.8664],
  "เชียงใหม่": [18.7893, 98.7337],
  "แพร่": [18.1955, 100.0648],};

const GROUPS = {
  building:       { th: 'อาคาร',            desc: 'อาคารและสิ่งปลูกสร้าง' },
  infrastructure: { th: 'โครงสร้างพื้นฐาน', desc: 'ระบบน้ำ ระบบจัดการขยะ และสาธารณูปโภค' },
};

const STATUS = {
  unfinished: { th: 'สร้างไม่เสร็จ', desc: 'ก่อสร้างค้าง ไม่เคยแล้วเสร็จ' },
  abandoned:  { th: 'ทิ้งร้าง',      desc: 'เคยใช้งาน แล้วถูกปล่อยร้าง' },
  unused:     { th: 'เสร็จแต่ไม่ใช้', desc: 'สร้างเสร็จ แต่ไม่เคยเปิดใช้เต็มที่' },
};

const AGENCY_TYPES = {
  ministry:   'ส่วนราชการ',
  autonomous: 'องค์กรอิสระ / องค์การมหาชน',
  school:     'สถานศึกษา',
  hospital:   'โรงพยาบาล',
  local:      'องค์กรปกครองส่วนท้องถิ่น',
  soe:        'รัฐวิสาหกิจ',
  unknown:    'ไม่ระบุในข้อมูลต้นทาง',
};

const REGION_NAMES = {
  north: 'เหนือ', northeast: 'อีสาน', central: 'กลาง',
  west: 'ตะวันตก', east: 'ตะวันออก', south: 'ใต้',
};
